@startuml
left to right direction
skinparam classAttributeIconSize 0

class user_profile_set {
  + get_name()
  + required_sample_data()
  # calculate_sample()
}

class user_track_forums {
  + get_name()
  + required_sample_data()
  # calculate_sample()
}

class upcoming_activities_due {
  + based_on_assumptions()
  + always_update_analysis_time()
  + can_use_timesplitting()
  + get_name()
  + get_insight_subject()
  # classes_description()
  + ignored_predicted_classes()
  + get_analyser_class()
  + is_valid_analysable()
  + is_valid_sample()
  # calculate_sample()
  + link_insights_report()
  + get_insight_body_for_prediction()
  + prediction_actions()
}

class devicekey {
  + update_device_public_key()
}

class prepare_private_files_for_edition {
  + execute_parameters()
  + execute()
  + execute_returns()
}

class search_identity {
  + execute_parameters()
  + execute()
  + execute_returns()
}

class update_private_files {
  + execute_parameters()
  + execute()
  + execute_returns()
}

class update_user_device_public_key {
  + execute_parameters()
  + execute()
  + execute_returns()
}

class user_summary_exporter {
  # get_other_values()
  # get_format_parameters_for_department()
  # get_format_parameters_for_institution()
  + define_properties()
  + define_other_properties()
}

class fields {
  # context
  # allowcustom
  # purposes
  # include
  # exclude
  # uniqueidentifier
  # fields
  # __construct()
  + empty()
  + for_identity()
  + for_userpic()
  + for_name()
  + with_userpic()
  + with_name()
  + with_identity()
  + including()
  + excluding()
  + get_required_fields()
  + get_picture_fields()
  + get_name_fields()
  + get_identity_fields()
  + get_sql()
  + get_sql_fullname()
  + get_display_name()
  + reset_unique_identifier()
  + match_custom_field()
}

class calendar_form {
  + definition()
  + definition_after_data()
}

class contactsitesupport_form {
  + definition()
  + validation()
}

class contentbank_user_preferences_form {
  + definition()
}

class defaulthomepage_form {
  + definition()
}

class private_files {
  + definition()
  + validation()
  # get_emaillink()
  + check_access_for_dynamic_submission()
  # get_context_for_dynamic_submission()
  + get_options()
  + process_dynamic_submission()
  + set_data_for_dynamic_submission()
  # get_page_url_for_dynamic_submission()
}

class profile_category_form {
  # definition()
  + validation()
  # get_context_for_dynamic_submission()
  # check_access_for_dynamic_submission()
  + process_dynamic_submission()
  + set_data_for_dynamic_submission()
  # get_page_url_for_dynamic_submission()
}

class profile_field_form {
  + field
  # fieldrecord
  + definition()
  + definition_after_data()
  + validation()
  + editors()
  # get_context_for_dynamic_submission()
  # check_access_for_dynamic_submission()
  + process_dynamic_submission()
  + set_data_for_dynamic_submission()
  # get_page_url_for_dynamic_submission()
  + get_field_record()
}

class after_login_completed {
}

class before_user_deleted {
  + __construct()
}

class before_user_updated {
  + __construct()
}

class extend_bulk_user_actions {
  - actions
  + get_hook_description()
  + get_hook_tags()
  + get_deprecated_plugin_callbacks()
  + add_action()
  + get_actions()
  + find_action_category()
}

class extend_default_homepage {
  - options
  + __construct()
  + add_option()
  + get_options()
}

class extend_user_menu {
  + __construct()
  + add_navitem()
  + get_navitems()
}

class category {
  - after
  - name
  - title
  - nodes
  - classes
  - properties
  + __construct()
  + add_node()
  + sort_nodes()
  # validate_after_order()
  # find_nodes_after()
  + __get()
}

class manager {
  + build_tree()
}

class node {
  - parentcat
  - name
  - after
  - title
  - url
  - content
  - icon
  - classes
  - properties
  + __construct()
  + __get()
}

class renderer {
  + render_tree()
  + render_category()
  + render_node()
}

class tree {
  - categories
  - nodes
  - properties
  + add_node()
  + add_category()
  + sort_categories()
  # attach_nodes_to_categories()
  # find_categories_after()
  + __get()
}

class participants_filter {
  # get_filtertypes()
  # get_enrolmentstatus_filter()
  # get_roles_filter()
  # get_enrolments_filter()
  # get_groups_filter()
  # get_accesssince_filter()
  # get_country_filter()
  # get_keyword_filter()
  + export_for_template()
}

class status_field {
  # enrolinstancename
  # coursename
  # fullname
  # status
  # timestart
  # timeend
  # timeenrolled
  # enrolactions
  # statusactive
  # statussuspended
  # statusnotcurrent
  + __construct()
  + export_for_template()
  + set_status()
}

class user_roles_editable {
  - context
  - courseroles
  - profileroles
  - viewableroles
  - assignableroles
  + __construct()
  + export_for_template()
  + update()
}

class provider {
  + get_metadata()
  + get_contexts_for_userid()
  + get_users_in_context()
  + export_user_data()
  + delete_data_for_all_users_in_context()
  + delete_data_for_users()
  + delete_data_for_user()
  # delete_user_data()
  # export_user()
  # export_lastaccess()
  # export_password_resets()
  # export_user_devices()
  # export_course_requests()
  # export_password_history()
  # export_user_session_data()
  + export_user_preferences()
}

class users {
  + get_name()
  # initialise()
  + get_default_columns()
  + get_default_filters()
  + get_default_conditions()
  + get_default_condition_values()
  + get_default_column_sorting()
}

class preferences {
  + get_preferences()
  + set_preferences()
  + set_preference()
  # set_single_preference()
  # check_user()
  # standardise_value()
}

class user_preferences_response {
  + __construct()
}

class course_teacher {
  # levels
  + get_component_name()
  + get_document_recordset()
  + get_document()
  + check_access()
  + get_context_url()
  + get_document_display_title()
  - get_user()
  + get_category_names()
  + get_doc_url()
}

class user {
  + get_document_recordset()
  + get_document()
  + get_document_display_title()
  + check_access()
  + get_doc_url()
  + get_context_url()
  + uses_file_indexing()
  + get_search_fileareas()
  + get_component_name()
  + get_doc_icon()
  + get_category_names()
}

class participants {
  # courseid
  # countries
  # groups
  # extrafields
  # course
  # context
  # allroles
  # allroleassignments
  # assignableroles
  # profileroles
  # filterset
  - viewableroles
  + baseurl
  + out()
  + col_select()
  + col_fullname()
  + col_roles()
  + col_groups()
  + col_country()
  + col_lastaccess()
  + col_status()
  + other_cols()
  + query_db()
  # show_hide_link()
  + set_filterset()
  + guess_base_url()
  + get_context()
  + has_capability()
}

class participants_filterset {
  + get_required_filters()
  + get_optional_filters()
}

class participants_search {
  # filterset
  # course
  # context
  # userfields
  + __construct()
  + get_participants()
  + get_total_participants_count()
  # get_participants_sql()
  # get_enrolled_sql()
  # get_enrol_method_sql()
  # get_status_sql()
  # get_groups_jointype()
  # get_roles_sql()
  # get_country_sql()
  # get_keywords_search_sql()
}

core_analytics\local\indicator\linear <|-- user_profile_set
core_analytics\local\indicator\binary <|-- user_track_forums
core_analytics\local\target\binary <|-- upcoming_activities_due
external_api <|-- prepare_private_files_for_edition
external_api <|-- search_identity
external_api <|-- update_private_files
external_api <|-- update_user_device_public_key
core\external\exporter <|-- user_summary_exporter
core_form\dynamic_form <|-- private_files
dynamic_form <|-- profile_category_form
dynamic_form <|-- profile_field_form
Psr\EventDispatcher\StoppableEventInterface <|.. after_login_completed
StoppableEventInterface <|.. before_user_deleted
deprecated_callback_replacement <|.. extend_bulk_user_actions
described_hook <|.. extend_bulk_user_actions
plugin_renderer_base <|-- renderer
core\output\datafilter <|-- participants_filter
core\output\inplace_editable <|-- user_roles_editable
core_privacy\local\metadata\provider <|.. provider
core_privacy\local\request\core_userlist_provider <|.. provider
core_privacy\local\request\subsystem\provider <|.. provider
core_privacy\local\request\user_preference_provider <|.. provider
datasource <|-- users
core\router\schema\response\response <|-- user_preferences_response
core_search\base <|-- course_teacher
core_search\base <|-- user
table_sql <|-- participants
dynamic_table <|.. participants
filterset <|-- participants_filterset
participants_search o-- context
participants_search o-- filterset
@enduml
