@startuml
skinparam classAttributeIconSize 0

class activity_base {
  # feedback_viewed_events()
  # feedback_check_grades()
  # get_timeclose_field()
}

class cognitive_depth {
  + get_name()
  + get_indicator_type()
  + get_cognitive_depth_level()
  # feedback_submitted_events()
  # feedback_replied()
}

class social_breadth {
  + get_name()
  + get_indicator_type()
  + get_social_breadth_level()
}

class overrides {
  # instance
  + get_instance_for_cache()
  + load_for_cache()
  + load_many_for_cache()
}

class custom_completion {
  + get_state()
  + get_defined_custom_rules()
  + get_custom_rule_descriptions()
  + get_sort_order()
}

class overview {
  - assign
  + __construct()
  + get_due_date_overview()
  + get_actions_overview()
  + get_extra_overview_items()
  - get_extra_submissions_overview()
  - get_extra_submission_status_overview()
}

class dates {
  - timedue
  # get_dates()
  + get_due_date()
}

class downloader {
  - manager
  - instance
  - userids
  - groupmode
  - groupid
  # filesforzipping
  - prefixes
  - downloadasfolders
  + __construct()
  + load_filelist()
  - load_student_filelist()
  - get_student_submission()
  - get_student_prefix()
  - load_submissionplugin_filelist()
  + download_zip()
  - get_zip_filename()
}

class all_submissions_downloaded {
  # preventcreatecall
  + create_from_assign()
  + get_description()
  + get_name()
  # init()
  # validate_data()
  + get_objectid_mapping()
}

class assessable_submitted {
  + create_from_submission()
  + get_description()
  + get_name()
  # init()
  # validate_data()
  + get_objectid_mapping()
  + get_other_mapping()
}

class base {
  # assign
  # legacylogdata
  + set_assign()
  + get_assign()
  + get_url()
  # validate_data()
}

class batch_set_marker_allocation_viewed {
  # preventcreatecall
  + create_from_assign()
  # init()
  + get_name()
  + get_description()
  # validate_data()
  + get_other_mapping()
}

class batch_set_workflow_state_viewed {
  # preventcreatecall
  + create_from_assign()
  # init()
  + get_name()
  + get_description()
  # validate_data()
  + get_other_mapping()
}

class course_module_instance_list_viewed {
  + create_from_course()
}

class course_module_viewed {
  # init()
  + get_objectid_mapping()
}

class extension_granted {
  # preventcreatecall
  + create_from_assign()
  + get_description()
  + get_name()
  # init()
  # validate_data()
  + get_objectid_mapping()
}

class feedback_viewed {
  + create_from_grade()
  # init()
  + get_name()
  + get_description()
  # validate_data()
  + get_objectid_mapping()
  + get_other_mapping()
}

class grading_form_viewed {
  # preventcreatecall
  + create_from_user()
  # init()
  + get_name()
  + get_description()
  # validate_data()
  + get_other_mapping()
}

class grading_table_viewed {
  # preventcreatecall
  + create_from_assign()
  # init()
  + get_name()
  + get_description()
  # validate_data()
  + get_other_mapping()
}

class group_override_created {
  # init()
  + get_name()
  + get_description()
  + get_url()
  # validate_data()
  + get_objectid_mapping()
  + get_other_mapping()
}

class group_override_deleted {
  # init()
  + get_name()
  + get_description()
  + get_url()
  # validate_data()
  + get_objectid_mapping()
  + get_other_mapping()
}

class group_override_updated {
  # init()
  + get_name()
  + get_description()
  + get_url()
  # validate_data()
  + get_objectid_mapping()
  + get_other_mapping()
}

class identities_revealed {
  # preventcreatecall
  + create_from_assign()
  + get_description()
  + get_name()
  # init()
  # validate_data()
  + get_objectid_mapping()
}

class marker_updated {
  # preventcreatecall
  + create_from_marker()
  + get_description()
  + get_name()
  # init()
  # validate_data()
  + get_objectid_mapping()
  + get_other_mapping()
}

class remove_submission_form_viewed {
  # preventcreatecall
  + create_from_user()
  # init()
  + get_name()
  + get_description()
  # validate_data()
  + get_other_mapping()
}

class reveal_identities_confirmation_page_viewed {
  # preventcreatecall
  + create_from_assign()
  # init()
  + get_name()
  + get_description()
  # validate_data()
  + get_other_mapping()
}

class statement_accepted {
  # preventcreatecall
  + create_from_submission()
  + get_description()
  + get_name()
  # init()
  # validate_data()
  + get_objectid_mapping()
}

class submission_confirmation_form_viewed {
  # preventcreatecall
  + create_from_assign()
  # init()
  + get_name()
  + get_description()
  # validate_data()
  + get_other_mapping()
}

class submission_created {
  # init()
  + get_name()
  # validate_data()
  + get_other_mapping()
}

class submission_duplicated {
  # preventcreatecall
  + create_from_submission()
  + get_description()
  + get_name()
  # init()
  # validate_data()
  + get_objectid_mapping()
}

class submission_form_viewed {
  # preventcreatecall
  + create_from_user()
  # init()
  + get_name()
  + get_description()
  # validate_data()
  + get_other_mapping()
}

class submission_graded {
  # preventcreatecall
  + create_from_grade()
  + get_description()
  + get_name()
  # init()
  # validate_data()
  + get_objectid_mapping()
}

class submission_locked {
  # preventcreatecall
  + create_from_user()
  + get_description()
  + get_name()
  # init()
  # validate_data()
  + get_objectid_mapping()
}

class submission_removed {
  + create_from_submission()
  # init()
  + get_name()
  + get_description()
  # validate_data()
  + get_objectid_mapping()
  + get_other_mapping()
}

class submission_status_updated {
  + create_from_submission()
  + get_description()
  + get_name()
  # init()
  # validate_data()
  + get_objectid_mapping()
  + get_other_mapping()
}

class submission_status_viewed {
  # preventcreatecall
  + create_from_assign()
  # init()
  + get_name()
  + get_description()
  # validate_data()
  + get_other_mapping()
}

class submission_unlocked {
  # preventcreatecall
  + create_from_user()
  + get_description()
  + get_name()
  # init()
  # validate_data()
  + get_objectid_mapping()
}

class submission_updated {
  # init()
  + get_name()
  # validate_data()
  + get_other_mapping()
}

class submission_viewed {
  + create_from_submission()
  # init()
  + get_name()
  + get_description()
  # validate_data()
  + get_objectid_mapping()
  + get_other_mapping()
}

class user_override_created {
  # init()
  + get_name()
  + get_description()
  + get_url()
  # validate_data()
  + get_objectid_mapping()
  + get_other_mapping()
}

class user_override_deleted {
  # init()
  + get_name()
  + get_description()
  + get_url()
  # validate_data()
  + get_objectid_mapping()
  + get_other_mapping()
}

class user_override_updated {
  # init()
  + get_name()
  + get_description()
  + get_url()
  # validate_data()
  + get_objectid_mapping()
  + get_other_mapping()
}

class workflow_state_updated {
  # preventcreatecall
  + create_from_user()
  + get_description()
  + get_name()
  # init()
  # validate_data()
  + get_objectid_mapping()
  + get_other_mapping()
}

class external_api {
  # generate_warning()
  # validate_assign()
  # get_user_or_group_submission()
}

class remove_submission {
  + execute_parameters()
  + execute()
  + execute_returns()
}

class start_submission {
  + execute_parameters()
  + execute()
  + execute_returns()
}

class gradeitems {
  + get_itemname_mapping_for_component()
  + get_advancedgrading_itemnames()
}

class group_observers {
  # resetinprogress
  + course_reset_started()
  + course_reset_ended()
  + group_deleted()
}

class secondary {
  # get_default_module_mapping()
}

class notification_helper {
  + get_due_soon_assignments()
  + get_overdue_assignments()
  + get_due_digest_assignments()
  + get_due_digest_assignments_for_user()
  + get_users_within_assignment()
  + send_due_soon_notification_to_user()
  + send_overdue_notification_to_user()
  + send_due_digest_notification_to_user()
  # get_time_now()
  # get_future_time()
  # get_day_start_and_end()
  # is_time_within_range()
  # has_user_been_sent_a_notification_already()
  # get_assignment_data()
}

class actionmenu {
  - cmid
  + __construct()
  + export_for_template()
}

class assign_header {
  + assign
  + context
  + showintro
  + coursemoduleid
  + subpage
  + preface
  + postfix
  + subpageurl
  + activity
  + __construct()
}

class assign_submission_status {
  + allowsubmissionsfromdate
  + alwaysshowdescription
  + submission
  + teamsubmissionenabled
  + teamsubmission
  + submissiongroup
  + submissiongroupmemberswhoneedtosubmit
  + submissionsenabled
  + locked
  + graded
  + duedate
  + cutoffdate
  + submissionplugins
  + returnaction
  + returnparams
  + courseid
  + coursemoduleid
  + view
  + canviewfullnames
  + canedit
  + cansubmit
  + extensionduedate
  + context
  + blindmarking
  + gradingcontrollerpreview
  + attemptreopenmethod
  + maxattempts
  + gradingstatus
  + preventsubmissionnotingroup
  + usergroups
  + timelimit
  + caneditowner
  + __construct()
}

class grading_actionmenu {
  # cmid
  # submissionpluginenabled
  # submissioncount
  # assign
  # showdownload
  # userinitials
  - hasviewblind
  + __construct()
  + export_for_template()
  - get_actions()
  - get_status_menu()
  - get_extra_filters_dropdown()
  - get_applied_extra_filters_count()
}

class grading_app {
  + userid
  + groupid
  + assignment
  + participants
  + __construct()
  + export_for_template()
}

class override_actionmenu {
  # currenturl
  # cm
  # canaccessallgroups
  # groups
  + __construct()
  # get_select_menu()
  # show_groups()
  # show_useroverride()
  + export_for_template()
}

class renderer {
  + htmlid
  + assign_files()
  + render_assign_files()
  - add_table_row_tuple()
  + render_assign_gradingmessage()
  + render_assign_form()
  + render_assign_user_summary()
  + render_assign_submit_for_grading_page()
  + render_footer()
  + render_assign_header()
  + render_assign_plugin_header()
  + render_assign_grading_summary()
  + render_assign_feedback_status()
  + render_assign_submission_status_compact()
  + render_assign_submission_status()
  + render_assign_attempt_history_chooser()
  + render_assign_attempt_history()
  + render_assign_submission_plugin_submission()
  + render_assign_grading_table()
  + render_assign_feedback_plugin_feedback()
  + render_assign_course_index_summary()
  # get_time_remaining()
  # htmllize_tree()
  # get_portfolio_button()
  # flexible_table()
  # moodleform()
  + render_grading_app()
  + submission_actionmenu()
  + render_user_submission_actionmenu()
  + render_override_actionmenu()
  + render_grading_actionmenu()
  + format_activity_text()
}

class timelimit_panel {
  # submission
  # assign
  + __construct()
  + export_for_template()
  - end_time()
}

class user_submission_actionmenu {
  # cmid
  # showsubmit
  # showedit
  # submission
  # teamsubmission
  # timelimit
  + __construct()
  # get_current_status()
  # is_submission_started()
  + export_for_template()
}

class helper {
  + is_penalty_enabled()
  + apply_penalty_to_user()
}

class penalty_recalculator {
  + recalculate_penalty()
}

class assignfeedback {
  + plugintype_supports_disabling()
  + get_enabled_plugins()
  + enable_plugin()
  + is_uninstall_allowed()
  + get_manage_url()
  + uninstall_cleanup()
  + get_settings_section_name()
  + load_settings()
}

class assignsubmission {
  + plugintype_supports_disabling()
  + get_enabled_plugins()
  + enable_plugin()
  + is_uninstall_allowed()
  + get_manage_url()
  + uninstall_cleanup()
  + get_settings_section_name()
  + load_settings()
}

interface assignfeedback_provider {
}

interface assignfeedback_user_provider {
}

interface assignsubmission_provider {
}

interface assignsubmission_user_provider {
}

class assign_plugin_request_data {
  # context
  # pluginobject
  # subcontext
  # user
  # userids
  # submissions
  # grades
  # assign
  + __construct()
  + set_userids()
  + get_context()
  + get_pluginobject()
  + get_subcontext()
  + get_user()
  + get_assign()
  + get_assignid()
  + get_userids()
  + get_submissionids()
  + get_submissions()
  + get_gradeids()
  + get_grades()
  + populate_submissions_and_grades()
}

class provider {
  + get_metadata()
  + get_contexts_for_userid()
  + get_users_in_context()
  + export_user_data()
  + delete_data_for_all_users_in_context()
  + delete_data_for_user()
  + delete_data_for_users()
  # delete_overrides_for_users()
  # get_graded_users()
  # store_assign_user_flags()
  # export_grade_data()
  # export_submission_data()
  + export_user_preferences()
  + export_overrides()
  # export_submission()
}

class useridlist {
  # teacherid
  # assignid
  # userids
  + __construct()
  + get_teacherid()
  + get_assignid()
  + get_userids()
  + add_from_sql()
}

class activity {
  + uses_file_indexing()
  + get_search_fileareas()
}

class shortlink_handler {
  + get_valid_linktypes()
  + process_shortlink()
}

class cron_task {
  + get_name()
  + execute()
}

class queue_all_assignment_due_digest_notification_tasks {
  + get_name()
  + execute()
}

class queue_all_assignment_due_soon_notification_tasks {
  + get_name()
  + execute()
}

class queue_all_assignment_overdue_notification_tasks {
  + get_name()
  + execute()
}

class queue_assignment_due_soon_notification_tasks_for_users {
  + execute()
}

class queue_assignment_overdue_notification_tasks_for_users {
  + execute()
}

class recalculate_penalties {
  + execute()
  + queue()
}

class send_assignment_due_digest_notification_to_user {
  + execute()
}

class send_assignment_due_soon_notification_to_user {
  + execute()
}

class send_assignment_overdue_notification_to_user {
  + execute()
}

core_analytics\local\indicator\community_of_inquiry_activity <|-- activity_base
activity_base <|-- cognitive_depth
activity_base <|-- social_breadth
data_source_interface <|.. overrides
activity_custom_completion <|-- custom_completion
core_courseformat\activityoverviewbase <|-- overview
overview *-- assign
overview o-- cm_info
activity_dates <|-- dates
downloader o-- assign
base <|-- all_submissions_downloaded
base <|-- assessable_submitted
core\event\base <|-- base
base <|-- batch_set_marker_allocation_viewed
base <|-- batch_set_workflow_state_viewed
core\event\course_module_instance_list_viewed <|-- course_module_instance_list_viewed
core\event\course_module_viewed <|-- course_module_viewed
base <|-- extension_granted
base <|-- feedback_viewed
base <|-- grading_form_viewed
base <|-- grading_table_viewed
core\event\base <|-- group_override_created
core\event\base <|-- group_override_deleted
core\event\base <|-- group_override_updated
base <|-- identities_revealed
base <|-- marker_updated
base <|-- remove_submission_form_viewed
base <|-- reveal_identities_confirmation_page_viewed
base <|-- statement_accepted
base <|-- submission_confirmation_form_viewed
base <|-- submission_created
base <|-- submission_duplicated
base <|-- submission_form_viewed
base <|-- submission_graded
base <|-- submission_locked
base <|-- submission_removed
base <|-- submission_status_updated
base <|-- submission_status_viewed
base <|-- submission_unlocked
base <|-- submission_updated
base <|-- submission_viewed
core\event\base <|-- user_override_created
core\event\base <|-- user_override_deleted
core\event\base <|-- user_override_updated
base <|-- workflow_state_updated
core_external\external_api <|-- external_api
external_api <|-- remove_submission
external_api <|-- start_submission
itemnumber_mapping <|.. gradeitems
advancedgrading_mapping <|.. gradeitems
core_secondary <|-- secondary
templatable <|.. actionmenu
renderable <|.. actionmenu
renderable <|.. assign_header
renderable <|.. assign_submission_status
templatable <|.. grading_actionmenu
renderable <|.. grading_actionmenu
grading_actionmenu --> assign
templatable <|.. grading_app
renderable <|.. grading_app
templatable <|.. override_actionmenu
renderable <|.. override_actionmenu
override_actionmenu o-- moodle_url
override_actionmenu o-- cm_info
plugin_renderer_base <|-- renderer
templatable <|.. timelimit_panel
renderable <|.. timelimit_panel
templatable <|.. user_submission_actionmenu
renderable <|.. user_submission_actionmenu
core_grades\penalty_recalculator <|-- penalty_recalculator
base <|-- assignfeedback
base <|-- assignsubmission
assign_plugin_request_data o-- context
assign_plugin_request_data o-- assign
core_privacy\local\metadata\provider <|.. provider
core_privacy\local\request\plugin\provider <|.. provider
core_privacy\local\request\user_preference_provider <|.. provider
core_privacy\local\request\core_userlist_provider <|.. provider
core_search\base_activity <|-- activity
shortlink_handler_interface <|.. shortlink_handler
core\task\scheduled_task <|-- cron_task
scheduled_task <|-- queue_all_assignment_due_digest_notification_tasks
scheduled_task <|-- queue_all_assignment_due_soon_notification_tasks
scheduled_task <|-- queue_all_assignment_overdue_notification_tasks
adhoc_task <|-- queue_assignment_due_soon_notification_tasks_for_users
adhoc_task <|-- queue_assignment_overdue_notification_tasks_for_users
adhoc_task <|-- recalculate_penalties
adhoc_task <|-- send_assignment_due_digest_notification_to_user
adhoc_task <|-- send_assignment_due_soon_notification_to_user
adhoc_task <|-- send_assignment_overdue_notification_to_user
@enduml
