@startuml course
left to right direction
skinparam classAttributeIconSize 0

class activities_due {
  + get_name()
  + required_sample_data()
  # calculate_sample()
  - get_provide_event_action_num_params()
}

class completion_enabled {
  + get_name()
  + required_sample_data()
  + calculate_sample()
}

class no_student {
  # studentroleids
  + get_name()
  + required_sample_data()
  + calculate_sample()
}

class no_teacher {
  # teacherroleids
  + get_name()
  + required_sample_data()
  + calculate_sample()
}

class potential_cognitive_depth {
  + get_name()
  + required_sample_data()
  + calculate_sample()
  # get_cognitive_indicator()
}

class potential_social_breadth {
  + get_name()
  + required_sample_data()
  + calculate_sample()
  # get_social_indicator()
  # level_not_accepted()
}

class course_competencies {
  # coursecompetencies
  # get_num_competencies_in_course()
  + get_name()
  # classes_description()
  + is_valid_analysable()
  # calculate_sample()
}

class course_completion {
  + get_name()
  # classes_description()
  + is_valid_analysable()
  # calculate_sample()
}

class course_dropout {
  + get_name()
  # classes_description()
  + is_valid_analysable()
  # calculate_sample()
}

class course_enrolments {
  # students
  + get_analyser_class()
  + can_use_timesplitting()
  + get_insight_subject()
  + get_insight_body()
  + is_valid_analysable()
  + is_valid_sample()
  + prediction_actions()
  + bulk_actions()
  + add_bulk_actions_js()
  # enrolment_active_during_analysis_time()
}

class course_gradetopass {
  # coursesgradetopass
  # coursesgrades
  # get_course_gradetopass()
  # get_user_grade()
  + get_name()
  # classes_description()
  + is_valid_analysable()
  # calculate_sample()
}

class no_access_since_course_start {
  + can_use_timesplitting()
  + get_name()
  + get_insight_body()
}

class no_recent_accesses {
  + based_on_assumptions()
  + get_name()
  + get_insight_body()
  + can_use_timesplitting()
  + is_valid_analysable()
  # calculate_sample()
}

class no_teaching {
  + based_on_assumptions()
  + can_use_timesplitting()
  + get_name()
  + get_insight_subject()
  + get_insight_body()
  + prediction_actions()
  # classes_description()
  + get_analyser_class()
  + is_valid_analysable()
  + is_valid_sample()
  # calculate_sample()
}

class course_image {
  # instance
  + get_instance_for_cache()
  + load_for_cache()
  # get_image_url_from_overview_files()
  + load_many_for_cache()
}

class cached_cm_info {
  + name
  + icon
  + iconcomponent
  + content
  + customdata
  + extraclasses
  + iconurl
  + onclick
}

class core_course_category {
  # coursecat0
  # coursecatfields
  # id
  # name
  # idnumber
  # description
  # descriptionformat
  # parent
  # sortorder
  # coursecount
  # visible
  # visibleold
  # timemodified
  # depth
  # path
  # theme
  # fromcache
  + __set()
  + __get()
  + __isset()
  + __unset()
  + get_plugins_callback_function()
  + getIterator()
  # __construct()
  + get()
  + top()
  + user_top()
  + get_many()
  + get_all()
  + get_default()
  # restore()
  + create()
  + update()
  + is_uservisible()
  + can_view_category()
  + can_view_course_info()
  + get_db_record()
  # get_tree()
  - get_cached_cat_tree()
  - rebuild_coursecattree_cache_contents()
  + count_all()
  + is_simple_site()
  # get_records()
  + role_assignment_changed()
  + user_enrolment_changed()
  + preload_course_contacts()
  + preload_custom_fields()
  # ensure_users_enrolled()
  # get_course_records()
  # get_not_visible_children_ids()
  # sort_records()
  + get_children()
  + get_all_children_ids()
  + has_manage_capability_on_any()
  + has_capability_on_any()
  + can_resort_any()
  + can_change_parent_any()
  + get_children_count()
  + has_children()
  + has_courses()
  + get_view_link()
  + search_courses()
  + search_courses_count()
  + get_courses()
  + get_courses_count()
  + can_delete()
  + can_delete_full()
  + delete_full()
  + move_content_targets_list()
  + can_move_content_to()
  + delete_move()
  + can_change_parent()
  # change_parent_raw()
  + change_parent()
  # hide_raw()
  + hide()
  # show_raw()
  + show()
  + get_formatted_name()
  + get_nested_name()
  + get_parents()
  + make_categories_list()
  + prepare_to_cache()
  + wake_from_cache()
  + can_create_top_level_category()
  + get_context()
  + has_manage_capability()
  + has_contentbank()
  + parent_has_manage_capability()
  + can_create_subcategory()
  + can_resort_subcategories()
  + can_resort_courses()
  + can_change_sortorder()
  + can_create_course()
  + can_edit()
  + can_review_roles()
  + can_review_permissions()
  + can_review_cohorts()
  + can_review_filters()
  + can_change_visibility()
  + can_move_courses_out_of()
  + can_move_courses_into()
  + can_restore_courses_into()
  + resort_subcategories()
  + resort_categories_cleanup()
  + resort_courses()
  + change_sortorder_by_one()
  + get_parent_coursecat()
  + can_request_course()
  - has_capabilities()
  + can_approve_course_requests()
  + page_setup()
  + get_nearest_editable_subcategory()
}

class cm_info {
  - modinfo
  - state
  - id
  - instance
  - idnumber
  - added
  - score
  - visible
  - visibleoncoursepage
  - visibleold
  - groupmode
  - groupingid
  - indent
  - completion
  - completiongradeitemnumber
  - completionpassgrade
  - completionview
  - completionexpected
  - availability
  - showdescription
  - extra
  - icon
  - iconcomponent
  - instancerecord
  - modname
  - module
  - name
  - sectionnum
  - sectionid
  - conditionscompletion
  - conditionsgrade
  - conditionsfield
  - available
  - availableinfo
  - uservisible
  - uservisibleoncoursepage
  - url
  - content
  - contentisformatted
  - customcmlistitem
  - extraclasses
  - iconurl
  - onclick
  - customdata
  - afterlink
  - afterediticons
  - deletioninprogress
  - downloadcontent
  - lang
  - enableaitools
  - enabledaiactions
  - standardproperties
  - standardmethods
  + __call()
  + __get()
  + getIterator()
  + __isset()
  + __set()
  + has_view()
  + get_url()
  - get_content()
  + get_formatted_content()
  + has_custom_cmlist_item()
  + get_name()
  + get_formatted_name()
  - get_extra_classes()
  - get_on_click()
  + get_custom_data()
  - get_after_link()
  + get_activitybadge()
  - get_after_edit_icons()
  + get_icon_url()
  + get_grouping_label()
  + get_module_type_name()
  - get_module_type_name_plural()
  + get_modinfo()
  + get_section_info()
  - get_section_id()
  + get_course()
  - get_course_id()
  - get_course_groupmode()
  - get_course_groupmodeforce()
  - get_effective_groupmode()
  - get_context()
  + get_course_module_record()
  + get_instance_record()
  + get_delegated_section_info()
  + set_content()
  + set_extra_classes()
  + set_icon_url()
  + set_on_click()
  + override_customdata()
  + set_after_link()
  + set_after_edit_icons()
  + set_name()
  + set_no_view_link()
  + set_user_visible()
  + set_custom_cmlist_item()
  + set_available()
  - check_not_view_only()
  + __construct()
  + create()
  - obtain_dynamic_data()
  + get_user_visible()
  + is_visible_on_course_page()
  + is_of_type_that_can_display()
  + is_stealth()
  - get_available()
  - get_available_info()
  - update_user_visible()
  + is_user_access_restricted_by_capability()
  - call_mod_function()
  - obtain_view_data()
}

class constants {
}

class course_request {
  # properties
  # summaryeditoroptions
  + prepare()
  + create()
  + summary_editor_options()
  + __construct()
  + __get()
  + __isset()
  + get_requester()
  + check_shortname_collision()
  + can_approve()
  + get_category()
  + approve()
  + reject()
  + delete()
  # notify()
  + can_request()
}

class course_handler {
  # singleton
  # parentcontext
  + create()
  + reset_caches()
  + can_configure()
  + can_edit()
  + can_view()
  + set_parent_context()
  # get_parent_context()
  + get_configuration_context()
  + get_configuration_url()
  + get_instance_context()
  + config_form_definition()
  + restore_instance_data_from_backup()
}

class core_course_deletecategory_form {
  # coursecat
  + definition()
  + validation()
}

class dndupload_ajax_processor {
  # course
  # context
  # section
  # type
  # module
  # cm
  # dnduploadhandler
  # displayname
  + __construct()
  # is_file_upload()
  + process()
  # handle_file_upload()
  # handle_other_upload()
  # display_name_from_file()
  # create_course_module()
  # prepare_module_data()
  # finish_setup_course_module()
  # send_response()
  - load_repository()
}

class dndupload_handler {
  # types
  # filehandlers
  # context
  + __construct()
  # register_type()
  # register_type_handler()
  # register_file_handler()
  + is_known_type()
  + has_type_handler()
  + has_file_handler()
  + get_handled_file_types()
  + get_js_data()
  # type_compare()
  - load_repository()
}

class core_course_editcategory_form {
  + definition()
  + get_description_editor_options()
  + validation()
}

class course_module_summary_exporter {
  # define_related()
  # get_other_values()
  # get_format_parameters_for_name()
  + define_other_properties()
}

class course_summary_exporter {
  + __construct()
  # define_related()
  # get_other_values()
  + define_properties()
  # get_format_parameters_for_summary()
  + define_other_properties()
  + get_course_image()
  + get_course_pattern()
  + get_course_progress()
  + coursecolor()
}

class get_enrolled_courses_with_action_events_by_timeline_classification {
  + execute_parameters()
  + execute()
  + execute_returns()
}

class helper_for_get_mods_by_courses {
  + standard_coursemodule_element_values()
  + format_name_and_intro()
  + standard_coursemodule_elements_returns()
}

class view_module_instance_list {
  + execute_parameters()
  + execute()
  + execute_returns()
}

class reject_course_request {
  + definition()
}

class request_course {
  + definition()
  + validation()
}

class tags_form {
  + definition()
}

class after_course_created {
  + __construct()
}

class after_course_updated {
  + __construct()
}

class after_form_definition {
  + __construct()
}

class after_form_definition_after_data {
  + __construct()
}

class after_form_submission {
  + __construct()
  + get_data()
}

class after_form_validation {
  # errors
  + __construct()
  + get_data()
  + get_files()
  + get_errors()
  + add_errors()
}

class before_activitychooserbutton_exported {
  + __construct()
  + get_hook_description()
  + get_hook_tags()
  + get_activitychooserbutton()
  + get_section()
  + get_cm()
}

class before_course_deleted {
  + __construct()
}

class before_course_viewed {
  + course
  + __construct()
  + get_hook_description()
  + get_hook_tags()
}

class core_course_list_element {
  # record
  # coursecontacts
  # canaccess
  + __construct()
  + has_summary()
  + has_course_contacts()
  + get_course_contacts()
  + get_custom_fields()
  + has_custom_fields()
  + has_course_overviewfiles()
  + get_course_overviewfiles()
  + __isset()
  + __get()
  + __unset()
  + __set()
  + getIterator()
  + get_formatted_name()
  + get_formatted_fullname()
  + get_formatted_shortname()
  + can_access()
  + can_edit()
  + can_change_visibility()
  + get_context()
  + can_review_enrolments()
  + can_delete()
  + can_backup()
  + can_restore()
}

class activity_chooser_footer {
  # footerjspath
  # footertemplate
  # carouseltemplate
  + __construct()
  + get_footer_js_file()
  + get_footer_template()
  + get_carousel_template()
}

class content_item {
  + __construct()
  + get_component_name()
  + get_help()
  + get_archetype()
  + get_id()
  + get_name()
  + get_title()
  + get_link()
  + get_icon()
  + get_purpose()
  + get_other_purpose()
  + is_branded()
  + is_gradable()
}

class lang_string_title {
  - component
  - identifier
  + __construct()
  + get_value()
}

class string_title {
  - title
  + __construct()
  + get_value()
}

interface title {
}

class course_content_items_exporter {
  - contentitems
  + __construct()
  + define_properties()
  # get_other_values()
  # define_related()
}

class course_content_item_exporter {
  - contentitem
  + __construct()
  # define_properties()
  # define_other_properties()
  # get_other_values()
  # define_related()
}

class content_item_service_factory {
  + get_content_item_service()
}

class caching_content_item_readonly_repository {
  - cachestore
  - contentitemrepository
  + __construct()
  + find_all_for_course()
  + find_all()
}

class content_item_readonly_repository {
  - get_core_module_help_string()
  - get_subplugin_course_content_items()
  - get_subplugin_all_content_items()
  - filter_out_items_not_to_be_displayed()
  + find_all()
  + find_all_for_course()
}

interface content_item_readonly_repository_interface {
}

class content_item_service {
  - repository
  + __construct()
  - get_favourite_content_items_for_user()
  - get_recommendations()
  - get_content_favourites()
  + get_all_content_items()
  + get_content_items_by_name_pattern()
  - export_content_items()
  + get_content_items_for_user_in_course()
  + add_to_user_favourites()
  + remove_from_user_favourites()
  + toggle_recommendation()
}

class helper {
  # expandedcategories
  + get_course_detail_array()
  - get_contacts_by_role_details()
  + get_category_listitem_actions()
  + get_course_listitem_actions()
  + get_course_detail_actions()
  + action_course_change_sortorder_up_one()
  + action_course_change_sortorder_down_one()
  + action_course_change_sortorder_up_one_by_record()
  + action_course_change_sortorder_down_one_by_record()
  + action_course_change_sortorder_after_course()
  + action_course_show()
  + action_course_hide()
  + action_course_show_by_record()
  + action_course_hide_by_record()
  + action_category_change_sortorder_up_one()
  + action_category_change_sortorder_down_one()
  + action_category_change_sortorder_up_one_by_id()
  + action_category_change_sortorder_down_one_by_id()
  + action_category_hide()
  + action_category_show()
  + action_category_show_by_id()
  + action_category_hide_by_id()
  + action_category_resort_subcategories()
  + action_category_resort_courses()
  + action_category_move_courses_into()
  + get_management_viewmodes()
  + search_courses()
  + move_courses_into_category()
  + get_category_courses_visibility()
  + get_category_children_visibility()
  + record_expanded_category()
  + get_expanded_categories()
  + get_course_copy_capabilities()
  + can_copy_course()
}

class core_course_management_renderer {
  + enhance_management_interface()
  + management_form_start()
  + management_form_end()
  + category_listing()
  + category_listitem()
  + category_listing_actions()
  + category_listitem_actions()
  + render_action_menu()
  + category_bulk_actions()
  + course_listing()
  # listing_pagination()
  + course_listitem()
  + course_listing_actions()
  + course_listitem_actions()
  + course_bulk_actions()
  + course_search_bulk_actions()
  + course_detail()
  # detail_pair()
  + course_detail_actions()
  # action_button()
  + grid_start()
  + grid_end()
  + grid_column_start()
  + grid_column_end()
  + action_icon()
  + view_mode_selector()
  + search_listing()
  # search_pagination()
  + search_listitem()
  + search_listitem_actions()
  + accessible_skipto_links()
  + render_action_bar()
}

class modinfo {
  + cachedfields
  - course
  - sectioninfobynum
  - sectioninfobyid
  - delegatedsections
  - delegatedbycm
  - weights
  - userid
  - sectionmodules
  - cms
  - instances
  - groups
  - standardproperties
  # instancecache
  # cacheaccessed
  # mincacherevs
  + __get()
  + __isset()
  + __set()
  + get_course()
  + get_course_id()
  + get_user_id()
  + get_sections()
  + get_cms()
  + get_cm()
  + get_instances()
  + get_used_module_names()
  + get_instances_of()
  + get_instance_of()
  + sort_cm_array()
  - get_groups_all()
  + get_groups()
  + get_section_info_all()
  + get_listed_section_info_all()
  + get_section_info()
  + get_section_info_by_id()
  + get_section_info_by_component()
  + has_delegated_sections()
  + get_sections_delegated_by_cm()
  + clear_instance_cache()
  + instance()
  + __construct()
  # build_course_section_cache()
  + build_course_cache()
  # inner_build_course_cache()
  + purge_course_section_cache_by_id()
  + purge_course_section_cache_by_number()
  + purge_course_module_cache()
  + purge_course_caches()
  + purge_course_modules_cache()
  + get_array_of_activities()
  + purge_course_cache()
  + is_mod_type_visible_on_course()
  - get_content_weights()
  - calculate_section_weights()
}

class group_selector {
  - activegroup
  + __construct()
  - get_button_content()
  - get_dropdown_content()
  - get_label()
  - get_active_group()
  - get_group_mode()
}

class group_selector_button {
  + __construct()
  + export_for_template()
  + get_template_name()
}

class group_selector_dropdown_form {
  + __construct()
  + export_for_template()
  + get_template_name()
}

class initials_dropdown_form {
  + __construct()
  + export_for_template()
}

class initials_selector {
  + __construct()
  - get_current_filter_state_string()
  - render_initials_dropdown_form()
}

class user_selector {
  + __construct()
  - user_selector_output()
}

class user_selector_button {
  + __construct()
  + export_for_template()
  + get_template_name()
}

class activity_completion {
  + __construct()
  + export_for_template()
  - get_overrideby()
  - get_completion_details()
  - get_accessible_description()
}

class activity_dates {
  + __construct()
  + export_for_template()
}

class activity_icon {
  # title
  # extraclasses
  # colourize
  # iconsize
  # iconurl
  # purpose
  # isbranded
  # __construct()
  + from_cm_info()
  + from_modname()
  + set_title()
  + set_colourize()
  + set_extra_classes()
  + set_icon_size()
  + export_for_template()
  + get_icon_url()
  + is_branded()
  + get_colourize()
  + get_title()
  + get_extra_classes()
  + get_icon_classes()
  + get_icon_size()
  + get_purpose()
}

class activity_navigation {
  + prevlink
  + nextlink
  + activitylist
  + __construct()
  + export_for_template()
}

class core_course_bulk_activity_completion_renderer {
  + bulkcompletion()
  + defaultcompletion()
  + edit_bulk_completion()
  + edit_default_completion()
  + render_course_completion_action_bar()
}

class category_action_bar {
  # category
  + __construct()
  # get_category_select()
  # get_additional_category_options()
  + export_for_template()
}

class completion_action_bar {
  - courseid
  - currenturl
  + __construct()
  + export_for_template()
}

class content_export_link {
  + get_attributes()
}

class manage_categories_action_bar {
  # course
  # page
  # viewmode
  # heading
  # searchvalue
  + __construct()
  # get_dropdown()
  # get_category_select()
  # get_search_form()
  + export_for_template()
}

class activity_list {
  # modules
  # searchquery
  + __construct()
  + export_for_template()
}

class renderer {
  + render_activity_list()
}

class provider {
  + get_metadata()
  + get_contexts_for_userid()
  + get_users_in_context()
  + export_user_data()
  + export_context_data()
  + export_user_preferences()
  + delete_data_for_all_users_in_context()
  + delete_data_for_user()
  + delete_data_for_users()
}

class categories {
  + get_name()
  # initialise()
  + get_default_columns()
  + get_default_column_sorting()
  + get_default_filters()
  + get_default_conditions()
}

class courses {
  + get_name()
  # initialise()
  + get_default_columns()
  + get_default_filters()
  + get_default_conditions()
  + get_default_column_sorting()
}

class participants {
  # initialise()
  + get_name()
  + get_default_columns()
  + get_default_column_sorting()
  + get_default_filters()
  + get_default_conditions()
  + get_default_condition_values()
}

class access {
  # get_default_tables()
  # get_default_entity_title()
  + initialise()
  # get_all_columns()
  # get_all_filters()
}

class completion {
  # get_default_tables()
  # get_deprecated_tables()
  # get_default_entity_title()
  + initialise()
  # get_all_columns()
  # get_all_filters()
  + completion_progress()
  + get_days()
}

class course_category {
  # get_default_tables()
  # get_default_entity_title()
  + initialise()
  # get_all_columns()
  # get_all_filters()
  + get_context_join()
}

class enrolment {
  # get_default_tables()
  # get_default_entity_title()
  + initialise()
  # get_all_columns()
  - get_status_field_sql()
  # get_all_filters()
  + enrolment_name()
  + enrolment_values()
  + enrolment_status()
}

class course_management {
  + administer_course()
}

class tags_controller {
  + administer_tags()
}

class course_routes {
  + administer_course()
  + administer_tags()
}

class course {
  # levels
  + get_document_recordset()
  + get_document()
  + check_access()
  + get_doc_url()
  + get_context_url()
  + uses_file_indexing()
  + get_search_fileareas()
  + get_component_name()
  + get_doc_icon()
  + get_category_names()
}

class customfield {
  # levels
  + get_document_recordset()
  + get_document()
  + check_access()
  + get_doc_url()
  + get_context_url()
  + get_component_name()
  + get_doc_icon()
  + get_category_names()
}

class section {
  # levels
  + get_document_recordset()
  + get_document()
  + check_access()
  + get_doc_url()
  + get_context_url()
  + uses_file_indexing()
  + get_search_fileareas()
  + get_component_name()
  + get_doc_icon()
  + get_category_names()
}

class section_info {
  - _id
  - _sectionnum
  - _name
  - _visible
  - _summary
  - _summaryformat
  - _availability
  - _component
  - _itemid
  - _delegateinstance
  - _sequencecminfos
  - _isorphan
  - _conditionscompletion
  - _conditionsgrade
  - _conditionsfield
  - _available
  - _availableinfo
  - _uservisible
  - sectioncachedefaults
  - cachedformatoptions
  - sectionformatoptions
  - modinfo
  + hasactivites
  - standardproperties
  + __construct()
  + __isset()
  + __get()
  + get_available()
  - check_delegated_available()
  - get_availableinfo()
  + getIterator()
  - get_uservisible()
  - check_delegated_uservisible()
  - get_sequence()
  + get_sequence_cm_infos()
  - get_course()
  - get_modinfo()
  - get_section_number()
  + get_component_instance()
  + is_delegated()
  + is_orphan()
  + convert_for_section_cache()
}

class content_notification_task {
  + execute()
}

class course_delete_modules {
  + execute()
  + retry_until_success()
}

class regrade_final_grades {
  + create()
  + execute()
}

core_analytics\local\indicator\binary <|-- activities_due
core_analytics\local\indicator\binary <|-- completion_enabled
core_analytics\local\indicator\binary <|-- no_student
core_analytics\local\indicator\binary <|-- no_teacher
core_analytics\local\indicator\linear <|-- potential_cognitive_depth
core_analytics\local\indicator\linear <|-- potential_social_breadth
course_enrolments <|-- course_competencies
course_enrolments <|-- course_completion
course_enrolments <|-- course_dropout
core_analytics\local\target\binary <|-- course_enrolments
course_enrolments <|-- course_gradetopass
no_recent_accesses <|-- no_access_since_course_start
course_enrolments <|-- no_recent_accesses
core_analytics\local\target\binary <|-- no_teaching
data_source_interface <|.. course_image
renderable <|.. core_course_category
cacheable_object <|.. core_course_category
IteratorAggregate <|.. core_course_category
IteratorAggregate <|.. cm_info
cm_info o-- modinfo
core_customfield\handler <|-- course_handler
moodleform <|-- core_course_deletecategory_form
dndupload_ajax_processor *-- dndupload_handler
moodleform <|-- core_course_editcategory_form
core\external\exporter <|-- course_module_summary_exporter
core\external\exporter <|-- course_summary_exporter
external_api <|-- get_enrolled_courses_with_action_events_by_timeline_classification
external_api <|-- view_module_instance_list
moodleform <|-- reject_course_request
moodleform <|-- request_course
moodleform <|-- tags_form
after_form_definition o-- course_edit_form
after_form_definition o-- MoodleQuickForm
after_form_definition_after_data o-- course_edit_form
after_form_definition_after_data o-- MoodleQuickForm
after_form_validation o-- course_edit_form
described_hook <|.. before_activitychooserbutton_exported
before_activitychooserbutton_exported o-- activitychooserbutton
before_activitychooserbutton_exported o-- section_info
StoppableEventInterface <|.. before_course_deleted
described_hook <|.. before_course_viewed
IteratorAggregate <|.. core_course_list_element
content_item o-- title
content_item o-- moodle_url
title <|.. lang_string_title
title <|.. string_title
exporter <|-- course_content_items_exporter
exporter <|-- course_content_item_exporter
course_content_item_exporter o-- content_item
content_item_readonly_repository_interface <|.. caching_content_item_readonly_repository
caching_content_item_readonly_repository o-- cache
caching_content_item_readonly_repository o-- content_item_readonly_repository
content_item_readonly_repository_interface <|.. content_item_readonly_repository
content_item_service o-- content_item_readonly_repository_interface
plugin_renderer_base <|-- core_course_management_renderer
comboboxsearch <|-- group_selector
renderable <|.. group_selector_button
named_templatable <|.. group_selector_button
group_selector_button o-- context
renderable <|.. group_selector_dropdown_form
named_templatable <|.. group_selector_dropdown_form
group_selector_dropdown_form o-- context
renderable <|.. initials_dropdown_form
templatable <|.. initials_dropdown_form
comboboxsearch <|-- initials_selector
comboboxsearch <|-- user_selector
user_selector o-- moodle_url
renderable <|.. user_selector_button
named_templatable <|.. user_selector_button
user_selector_button o-- url
renderable <|.. activity_completion
templatable <|.. activity_completion
activity_completion o-- cm_info
activity_completion o-- cm_completion_details
renderable <|.. activity_dates
templatable <|.. activity_dates
renderable <|.. activity_icon
templatable <|.. activity_icon
activity_icon --> iconsize
activity_icon --> url
renderable <|.. activity_navigation
templatable <|.. activity_navigation
plugin_renderer_base <|-- core_course_bulk_activity_completion_renderer
manage_categories_action_bar <|-- category_action_bar
category_action_bar o-- moodle_page
templatable <|.. completion_action_bar
renderable <|.. completion_action_bar
completion_action_bar o-- moodle_url
renderable <|.. manage_categories_action_bar
manage_categories_action_bar o-- moodle_page
renderable <|.. activity_list
templatable <|.. activity_list
plugin_renderer_base <|-- renderer
core_privacy\local\metadata\provider <|.. provider
core_privacy\local\request\context_aware_provider <|.. provider
core_privacy\local\request\core_userlist_provider <|.. provider
core_privacy\local\request\plugin\provider <|.. provider
core_privacy\local\request\user_preference_provider <|.. provider
datasource <|-- categories
datasource <|-- courses
datasource <|-- participants
base <|-- access
base <|-- completion
base <|-- course_category
base <|-- enrolment
core_search\base <|-- course
core_search\base <|-- customfield
core_search\base <|-- section
IteratorAggregate <|.. section_info
adhoc_task <|-- content_notification_task
core\task\adhoc_task <|-- course_delete_modules
adhoc_task <|-- regrade_final_grades
@enduml
